image: python:3.7.0

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - apt-get update && apt-get install -q -y $(cat apt-pkgs.txt)
          - pip install -r requirements-dev.txt
          - flake8
