image: python:3.7.0

pipelines:
  default:
    - step:
        name: Build & Test
        caches:
          - pip
        script:
          - apt-get update && apt-get install -q -y $(cat apt-pkgs.txt)
          - pip install -r requirements-dev.txt

          # lint and test
          - flake8
          - pytest
