version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
      - 16379:16379

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  link_harvester: &WORKER
    image: crawler
    hostname: link_harvester
    build:
      context: .
    links:
      - rabbitmq:rabbitmq
      - redis:redis
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - BACKEND_URL=redis://redis:6379/0
    command: celery worker -A worker -Q harvest_links -l info -E

  distributer:
    <<: *WORKER
    hostname: distributer
    command: celery worker -A worker -Q distribute_chain -l info -E

  content_harvester:
    <<: *WORKER
    hostname: content_harvester
    command: celery worker -A worker -Q harvest_content -l info -E

  extractor:
    <<: *WORKER
    hostname: extractor
    command: celery worker -A worker -Q extract_nouns -l info -E

  aggregator:
    <<: *WORKER
    hostname: aggregator
    command: celery worker -A worker -Q aggregate_words -l info -E

  flower:
    <<: *WORKER
    hostname: flower
    ports:
      - 5555:5555
    command: celery flower -A worker
