version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    links:
      - elasticsearch:elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601

  redis:
    image: redis
    ports:
      - 6379:6379
      - 16379:16379
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: [
        'CMD', 'bash', '-c',
        'exec 3<> /dev/tcp/127.0.0.1/6379 && echo PING >&3 && head -1 <&3 | grep PONG'
      ]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ['CMD', 'rabbitmqctl', 'status']

  newscrawler:
    image: newscrawler
    build:
      context: .
    command: "true"

  harvester: &WORKER
    image: newscrawler
    hostname: harvester
    links:
      - rabbitmq:rabbitmq
      - redis:redis
      - elasticsearch
    depends_on:
      - rabbitmq
      - redis
      - elasticsearch
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - BACKEND_URL=redis://redis:6379/0
      # - BACKEND_URL=elasticsearch://elasticsearch:9200/newscrawler/results
    command: celery worker -A worker -Q harvest -l info -E
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ['CMD', 'celery', 'status', '-A', 'worker']

  distributer:
    <<: *WORKER
    hostname: distributer
    command: celery worker -A worker -Q distribute_chain -l info -E

  extractor:
    <<: *WORKER
    hostname: extractor
    command: celery worker -A worker -Q extract -l info -E

  aggregator:
    <<: *WORKER
    hostname: aggregator
    command: celery worker -A worker -Q aggregate_words -l info -E

  flower:
    <<: *WORKER
    hostname: flower
    ports:
      - 5555:5555
    command: celery flower -A worker
