version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
      - 16379:16379

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  worker:
    image: crawler
    build:
      context: .
    links:
      - rabbitmq:rabbitmq
      - redis:redis
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - BACKEND_URL=redis://redis:6379/0

  flower:
    image: crawler
    links:
      - rabbitmq:rabbitmq
      - redis:redis
    ports:
      - 5555:5555
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - BACKEND_URL=redis://redis:6379/0
    command: celery flower -A worker
