version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
      - 16379:16379
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: [
        'CMD', 'bash', '-c',
        'exec 3<> /dev/tcp/127.0.0.1/6379 && echo PING >&3 && head -1 <&3 | grep PONG'
      ]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ['CMD', 'rabbitmqctl', 'status']

  newscrawler:
    image: newscrawler
    build:
      context: .

  link_harvester: &WORKER
    image: newscrawler
    hostname: link_harvester
    links:
      - rabbitmq:rabbitmq
      - redis:redis
    depends_on:
      - redis
      - rabbitmq
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - BACKEND_URL=redis://redis:6379/0
    command: celery worker -A worker -Q harvest_links -l info -E
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ['CMD', 'celery', 'status', '-A', 'worker']

  distributer:
    <<: *WORKER
    hostname: distributer
    command: celery worker -A worker -Q distribute_chain -l info -E

  content_harvester:
    <<: *WORKER
    hostname: content_harvester
    command: celery worker -A worker -Q harvest_content -l info -E

  extractor:
    <<: *WORKER
    hostname: extractor
    command: celery worker -A worker -Q extract_nouns -l info -E

  aggregator:
    <<: *WORKER
    hostname: aggregator
    command: celery worker -A worker -Q aggregate_words -l info -E

  flower:
    <<: *WORKER
    hostname: flower
    ports:
      - 5555:5555
    command: celery flower -A worker
